# Generated by Django 3.0.7 on 2020-09-01 10:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='shipping_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
