# Generated by Django 2.2.16 on 2020-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=17)),
            ],
        ),
    ]
