# Generated by Django 2.2.16 on 2020-09-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
