# Generated by Django 2.2.16 on 2020-09-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paystack_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=49, null=True),
        ),
    ]
