# Generated by Django 2.2.16 on 2020-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200907_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=6226212, max_length=15),
            preserve_default=False,
        ),
    ]
